#!/bin/bash

# 許可されたプレフィックス一覧
readonly PREFIXES=(feat fix docs style refactor perf test chore ci build)
readonly PREFIX_REGEX="^($(IFS='|'; echo "${PREFIXES[*]}"):|Merge)"
readonly MSG=$(head -n 1 "$1")

if [[ ! $MSG =~ $PREFIX_REGEX ]]; then
  echo -n "Error: Commit message must start with one of: "
  (IFS=', '; echo "'${PREFIXES[*]// /', '}'" or 'Merge'.)
  echo "Your commit message was: $MSG"
  exit 1
fi