openapi: 3.0.3
info:
  title: Daycare Management API
  description: スマ登園のAPI仕様書
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: 開発環境

paths:
  /api/login:
    post:
      summary: Firebase認証後のログイン
      description: FirebaseのlocalId（uid）を使用してユーザー情報を返します
      operationId: login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestModel"
      responses:
        "200":
          description: ログイン成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponseModel"
        "401":
          $ref: "error.yaml#/components/responses/UnauthorizedErrorModel"

components:
  schemas:
    LoginRequestModel:
      type: object
      description: Firebase認証ログインリクエスト
      properties:
        localId:
          type: string
          description: FirebaseのlocalId（uid）
          example: "abcd1234efgh5678ijkl9012mnop3456"
          minLength: 10
          maxLength: 255
      required:
        - localId

    LoginResponseModel:
      type: object
      description: Firebase認証ログインレスポンス
      properties:
        success:
          type: boolean
          description: ログイン成功フラグ
          example: true
        message:
          type: string
          description: メッセージ
          example: "ログインが成功しました"
        user:
          $ref: "summaries.yaml#/components/schemas/UserSummaryModel"
      required:
        - success
        - message
