openapi: 3.0.3
info:
  title: Daycare Management API
  description: 保育園管理システムのAPI仕様書
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: 開発環境

paths:
  /api/students:
    get:
      summary: 生徒一覧取得
      description: 全生徒の一覧を取得します
      operationId: getStudents
      tags:
        - Student
      responses:
        '200':
          description: 生徒一覧取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentResponseModel'
        '500':
          description: サーバーエラー

components:
  schemas:
    StudentResponseModel:
      type: object
      description: 生徒レスポンスモデル
      properties:
        id:
          type: integer
          format: int64
          description: 生徒ID
          example: 1
        name:
          type: string
          maxLength: 50
          description: 生徒名
          example: "田中太郎"
        age:
          type: integer
          format: int32
          minimum: 0
          maximum: 20
          description: 年齢
          example: 5
        className:
          type: string
          maxLength: 50
          description: クラス名
          example: "ひまわり組"
      required:
        - id
        - name
        - age
        - className
