openapi: 3.0.3
info:
  title: Common Schemas
  description: 共通スキーマ定義
  version: 1.0.0

components:
  responses:
    UnauthorizedErrorModel:
      description: 認証失敗
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorizedErrorResponseModel"

  schemas:
    UnauthorizedErrorResponseModel:
      type: object
      properties:
        error:
          type: array
          items:
            $ref: "#/components/schemas/ApiErrorModel"

    ApiErrorModel:
      type: object
      properties:
        name:
          type: string
          description: エラーが発生したフィールド名
          example: name
        message:
          type: string
          description: エラーメッセージ
          example: "認証に失敗しました。ログインIDまたはパスワードが正しくありません。"
      required: [ "name", "message" ]
