openapi: 3.0.3
info:
  title: Common Schemas
  description: 共通スキーマ定義
  version: 1.0.0

components:
  responses:
    BadRequestErrorModel:
      description: リクエストが不正
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestErrorResponseModel"

    UnauthorizedErrorModel:
      description: 認証失敗
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorizedErrorResponseModel"

  schemas:
    BadRequestErrorResponseModel:
      type: object
      description: リクエストが不正な場合のエラーレスポンス
      properties:
        error:
          type: array
          items:
            $ref: "#/components/schemas/ApiErrorModel"

    UnauthorizedErrorResponseModel:
      type: object
      description: 認証に失敗した場合のエラーレスポンス
      properties:
        error:
          type: array
          items:
            $ref: "#/components/schemas/ApiErrorModel"

    ApiErrorModel:
      type: object
      properties:
        name:
          type: string
          description: エラーが発生したフィールド名
          example: name
        message:
          type: string
          description: エラーメッセージ
          example: "エラーが発生しました。"
      required: [ "name", "message" ]
