spring:
  datasource:
    url: jdbc:postgresql://db:5432/daycare
    username: daycareuser
    password: daycarepass
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    locations: filesystem:migration
    validate-on-migrate: false
    out-of-order: true
    clean-disabled: false
    clean-on-validation-error: false
    # リピータブルマイグレーションを確実に実行するための設定
    repeatable-sql-migration-prefix: R
    sql-migration-suffixes: .sql
    ignore-migration-patterns: true
server:
  port: 8080
