spring:
  datasource:
    url: jdbc:postgresql://db:5432/daycare
    username: daycareuser
    password: daycarepass
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    locations: filesystem:migration
    validate-on-migrate: false
    clean-disabled: false
    clean-on-validation-error: false
    sql-migration-suffixes: .sql
server:
  port: 8080
