spring:
  datasource:
    url: jdbc:postgresql://db:5432/daycare
    username: daycareuser
    password: daycarepass
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080 