/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.example.daycare.presentation.apis

import com.example.daycare.presentation.model.ErrorResponse
import com.example.daycare.presentation.model.LoginRequestModel
import com.example.daycare.presentation.model.LoginResponseModel
import com.example.daycare.presentation.model.StudentResponseModel
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface ApiApi {

    @Operation(
        tags = ["Student",],
        summary = "生徒一覧取得",
        operationId = "getStudents",
        description = """全生徒の一覧を取得します""",
        responses = [
            ApiResponse(responseCode = "200", description = "生徒一覧取得成功", content = [Content(array = ArraySchema(schema = Schema(implementation = StudentResponseModel::class)))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = ErrorResponse::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = ErrorResponse::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/api/students"],
            produces = ["application/json"]
    )
    fun getStudents(): ResponseEntity<List<StudentResponseModel>>

    @Operation(
        tags = ["Auth",],
        summary = "ログイン",
        operationId = "login",
        description = """ログインIDとパスワードで認証し、JWTトークンを返します""",
        responses = [
            ApiResponse(responseCode = "200", description = "ログイン成功", content = [Content(schema = Schema(implementation = LoginResponseModel::class))]),
            ApiResponse(responseCode = "401", description = "認証失敗", content = [Content(schema = Schema(implementation = ErrorResponse::class))]),
            ApiResponse(responseCode = "423", description = "アカウントロック", content = [Content(schema = Schema(implementation = ErrorResponse::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = ErrorResponse::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/api/login"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun login(@Parameter(description = "", required = true) @Valid @RequestBody loginRequestModel: LoginRequestModel): ResponseEntity<LoginResponseModel>
}
