name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "backend/**/*.kt"
      - "backend/**/*.java"
      - "backend/**/*.gradle"
      - "backend/**/*.gradle.kts"
      - "backend/**/*.yml"
      - "backend/**/*.yaml"
      - "backend/**/*.properties"
      - "backend/**/*.sql"
      - "backend/build.gradle.kts"
      - "backend/settings.gradle.kts"
      - "backend/gradle/**"
      - "backend/migration/**"
      - "backend/openapi/**"
      - ".github/workflows/backend-check.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "backend/**/*.kt"
      - "backend/**/*.java"
      - "backend/**/*.gradle"
      - "backend/**/*.gradle.kts"
      - "backend/**/*.yml"
      - "backend/**/*.yaml"
      - "backend/**/*.properties"
      - "backend/**/*.sql"
      - "backend/build.gradle.kts"
      - "backend/settings.gradle.kts"
      - "backend/gradle/**"
      - "backend/migration/**"
      - "backend/openapi/**"
      - ".github/workflows/backend-check.yml"

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: backend

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
          allow-snapshots: false

      - name: Run ktlint check
        run: ./gradlew ktlintCheck --no-daemon
        working-directory: backend

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon
        working-directory: backend

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: daycare
          POSTGRES_USER: daycareuser
          POSTGRES_PASSWORD: daycarepass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: backend

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
          allow-snapshots: false

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U daycareuser; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
        working-directory: backend

      - name: Run database migrations
        run: ./gradlew flywayMigrate --no-daemon
        working-directory: backend

      - name: Generate JOOQ classes
        run: ./gradlew generateJooq --no-daemon
        working-directory: backend

      - name: Run tests
        run: ./gradlew test --no-daemon
        working-directory: backend
