name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**/*.kt'
      - 'backend/**/*.java'
      - 'backend/**/*.gradle'
      - 'backend/**/*.gradle.kts'
      - 'backend/**/*.yml'
      - 'backend/**/*.yaml'
      - 'backend/**/*.properties'
      - 'backend/**/*.sql'
      - 'backend/build.gradle.kts'
      - 'backend/settings.gradle.kts'
      - 'backend/gradle/**'
      - 'backend/migration/**'
      - 'backend/openapi/**'
      - '.github/workflows/backend-check.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**/*.kt'
      - 'backend/**/*.java'
      - 'backend/**/*.gradle'
      - 'backend/**/*.gradle.kts'
      - 'backend/**/*.yml'
      - 'backend/**/*.yaml'
      - 'backend/**/*.properties'
      - 'backend/**/*.sql'
      - 'backend/build.gradle.kts'
      - 'backend/settings.gradle.kts'
      - 'backend/gradle/**'
      - 'backend/migration/**'
      - 'backend/openapi/**'
      - '.github/workflows/backend-check.yml'

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        working-directory: backend

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 1
          allow-snapshots: false
          root-directory: backend

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon
        working-directory: backend

      - name: Run tests
        run: ./gradlew test -x generateJooq --no-daemon
        working-directory: backend
