name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - "frontend/**/*.js"
      - "frontend/**/*.jsx"
      - "frontend/**/*.ts"
      - "frontend/**/*.tsx"
      - "frontend/**/*.json"
      - "frontend/**/*.scss"
      - "frontend/**/*.css"
      - "frontend/package.json"
      - "frontend/package-lock.json"
      - ".github/workflows/frontend-check.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "frontend/**/*.js"
      - "frontend/**/*.jsx"
      - "frontend/**/*.ts"
      - "frontend/**/*.tsx"
      - "frontend/**/*.json"
      - "frontend/**/*.scss"
      - "frontend/**/*.css"
      - "frontend/package.json"
      - "frontend/package-lock.json"
      - ".github/workflows/frontend-check.yml"

jobs:
  frontend:
    name: Frontend Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Check ESLint
        run: npm run lint
        working-directory: frontend

      - name: Check Prettier formatting
        run: npm run format:check
        working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: frontend
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run tests
        run: npm test -- --watchAll=false --coverage
        working-directory: frontend
